music/greedymusic/urls.py
from django.conf.urls import url

from . import views


app_name = "greedymusic"
urlpatterns = [
				url(r'^$', views.index, name='index'),
				url(r'^track/(?P<track_id>[0-9]+)/$', views.detailTrack,name='detailTrack'),
				url(r'^tracks/(?P<pno>[0-9]+)/$', views.tracks, name='tracks'),
				url(r'^search/$', views.search,name='search'),
				url(r'^editTrack/(?P<track_id>[0-9]+)/$', views.editTrack,name='editTrack'),
				url(r'^addTrack/$', views.addTrack,name='addTrack'),
				url(r'^submitAdd/$', views.submitAdd,name='submitAdd'),
				url(r'^submitEdit/(?P<track_id>[0-9]+)/$', views.submitEdit,name='submitEdit'),
				url(r'^genres/$', views.genres, name='genres'),
				url(r'^editGenre/(?P<genre_id>[0-9]+)/$', views.editGenre,name='editGenre'),
				url(r'^addGenre/$', views.addGenre,name='addGenre'),
				url(r'^submitGenreAdd/$', views.submitGenreAdd,name='submitGenreAdd'),
				url(r'^submitGenreEdit/(?P<genre_id>[0-9]+)/$', views.submitGenreEdit,name='submitGenreEdit'),
				url(r'^genres/(?P<genre_id>[0-9]+)/$', views.detailGenre,name='detailGenre'),

			  ]

music/music/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^greedymusic/', include('greedymusic.urls')),
    url(r'^admin/', admin.site.urls),
]

music/greedymusic/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Track(models.Model):
	title = models.CharField(max_length=50)
	genre = models.CharField(max_length=50)
	rating = models.IntegerField(default=0)

	def __str__(self):
		return self.title


class Genre(models.Model):
	#track = models.ForeignKey(Track, on_delete=models.CASCADE)
	genre_name = models.CharField(max_length=50)

	def __str__(self):
		return self.genre_name

music/greedymusic/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from .models import Track, Genre
from django.db.models import Q
# Create your views here.
def index(request):
	return render(request, 'greedymusic/index.html')

def tracks(request,pno):
	track_list = Track.objects.order_by('id')
	for track in track_list:
		track.remaining = range(5-track.rating)
		track.rating = range(track.rating)
	if(len(track_list)%5==0):
		pages = len(track_list)/5
	else:
		pages = len(track_list)/5 + 1
	pno = int(pno)
	l = []
	if((pno-1)*5+5 > len(track_list)):
		for i in range((pno-1)*5, len(track_list)):
			l.append(track_list[i])	
	else:
		for i in range((pno-1)*5,(pno-1)*5 + 5):
			l.append(track_list[i])
	


	return render(request, 'greedymusic/tracks.html', {'track_list':l,'pages':range(1,pages+1)})

def detailTrack(request, track_id):
	t = Track.objects.get(pk=track_id)
	t.remaining = range(5-t.rating)
	t.rating = range(t.rating)
	return render(request, 'greedymusic/track.html', {'track':t})

def editTrack(request, track_id):
	q = Track.objects.get(pk=track_id)
	return render(request, 'greedymusic/editTrack.html', {'id':track_id,'title':q.title,'genre':q.genre,'rating':q.rating})

def submitEdit(request,track_id):
	if request.method=='POST':
		title = request.POST['title']
		genre = request.POST['genre']
		rating = request.POST['rating']
		t = Track.objects.get(pk=track_id)
		t.title = title
		genres = genre.split(",")
		t.genre = " | ".join(genres)
		t.rating = rating
		t.save()

		for gen in genres:
			ge = Genre.objects.filter(genre_name  = gen)
			if(len(ge)==0):
				g = Genre(genre_name=genre)
				g.save()


		track_list = Track.objects.order_by('id')
		for track in track_list:
			track.remaining = range(5-track.rating)
			track.rating = range(track.rating)
		return render(request, 'greedymusic/tracks.html', {'track_list':track_list})

def search(request):
	keyword = request.POST['keyword']
	results = Track.objects.filter(Q(title__icontains=keyword) | Q(genre__icontains=keyword)).order_by('id')
	for track in results:
		track.remaining = range(5-track.rating)
		track.rating = range(track.rating)
	return render(request, 'greedymusic/search.html', {'track_list':results}) 

def addTrack(request):
	return render(request, 'greedymusic/addTrack.html')

def submitAdd(request):
	if request.method == 'POST':
		title = request.POST['title']
		genre = request.POST['genre']
		rating = request.POST['rating']
		genres = genre.split(",")
		genre = " | ".join(genres)
		t = Track(title=title, genre=genre, rating=rating)
		t.save()

		for gen in genres:
			ge = Genre.objects.filter(genre_name  = gen)
			if(len(ge)==0):
				g = Genre(genre_name=gen)
				g.save()
				
		track_list = Track.objects.order_by('id')
		for track in track_list:
			track.remaining = range(5-track.rating)
			track.rating = range(track.rating)
		return render(request, 'greedymusic/tracks.html', {'track_list':track_list})



def addGenre(request):
	return render(request, 'greedymusic/addGenre.html')

def submitGenreAdd(request):
	if request.method == 'POST':
		name = request.POST['name']
		g = Genre(genre_name=name)
		g.save()
		genre_list = Genre.objects.order_by('id')
		return render(request, 'greedymusic/genres.html', {'genre_list':genre_list})

def submitGenreEdit(request,genre_id):
	if request.method == 'POST':
		name = request.POST['name']
		g = Genre.objects.get(pk=genre_id)
		cgname = g.genre_name
		g.genre_name = name
		g.save()
		track_list = Track.objects.all()
		for t in track_list:
			tgenre = t.genre.split(" | ")
			for i in range(0,len(tgenre)):
				if(tgenre[i]==cgname):
					tgenre[i] = name
			t.genre = " | ".join(tgenre)
			t.save()
		genre_list = Genre.objects.order_by('id')
		return render(request, 'greedymusic/genres.html', {'genre_list':genre_list})

def genres(request):
	genre_list = Genre.objects.order_by('id')
	return render(request, 'greedymusic/genres.html', {'genre_list':genre_list})

def editGenre(request, genre_id):
	q = Genre.objects.get(pk=genre_id)
	return render(request, 'greedymusic/editGenre.html', {'id':genre_id,'genre_name':q.genre_name})

def detailGenre(request, genre_id):
	g = Genre.objects.get(pk=genre_id)
	glist = []
	glist.append(g)
	return render(request, 'greedymusic/genres.html', {'genre_list':glist})

music/greedymusic/templates/greedymusic/addGenre.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>

	<div class="row">

		<div class="col-md-4 col-md-offset-4">

			<form method="POST" action="{% url 'greedymusic:submitGenreAdd' %}">
				{% csrf_token %}
			  <div class="form-group">
			    <label for="name">Name</label>
			    <input type="text" class="form-control" name="name" id="name" placeholder="Name" required>
			  </div>
			  <div class="text-center">
			  	<button type="submit" class="btn btn-primary text-center">Add New Genre</button>
		  	  </div>
			</form>

		</div>

	</div>

</body>

music/greedymusic/templates/greedymusic/addTrack.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>

	<div class="row">

		<div class="col-md-4 col-md-offset-4">

			<form method="POST" action="{% url 'greedymusic:submitAdd' %}">
				{% csrf_token %}
			  <div class="form-group">
			    <label for="title">Title</label>
			    <input type="text" class="form-control" name="title" id="title" placeholder="Title" required>
			  </div>
			  <div class="form-group">
			    <label for="genre">Genre</label>
			    <input type="text" class="form-control" name="genre" id="genre" placeholder="Genre" required>
			  </div>
			  <div class="form-group">
			    <label for="rating">Rating</label>
			    <input type="number" class="form-control" name="rating" id="rating" placeholder="Rating" required>
			  </div>
			  <div class="text-center">
			  	<button type="submit" class="btn btn-primary text-center">Add New Track</button>
		  	  </div>
			</form>

		</div>

	</div>

</body>

music/greedymusic/templates/greedymusic/editGenre.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>

	<div class="row">

		<div class="col-md-4 col-md-offset-4">

			<form method="POST" action="{% url 'greedymusic:submitGenreEdit' id %}">
				{% csrf_token %}
			  <div class="form-group">
			    <label for="name">Name</label>
			    <input type="text" class="form-control" name="name" value="{{ genre_name }}" id="name" placeholder="Name" required>
			  </div>
			  <div class="text-center">
			  	<button type="submit" class="btn btn-primary text-center">Save</button>
		  	  </div>
			</form>

		</div>

	</div>

</body>

music/greedymusic/templates/greedymusic/editTrack.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>

	<div class="row">

		<div class="col-md-4 col-md-offset-4">

			<form method="POST" action="{% url 'greedymusic:submitEdit' id%}">
				{% csrf_token %}
			  <div class="form-group">
			    <label for="title">Title</label>
			    <input type="text" class="form-control" name="title" id="title" value="{{ title }}"placeholder="Title" required>
			  </div>
			  <div class="form-group">
			    <label for="genre">Genre</label>
			    <input type="text" class="form-control" name="genre" value="{{ genre }}" id="genre" placeholder="Genre" required>
			  </div>
			  <div class="form-group">
			    <label for="rating">Rating</label>
			    <input type="number" class="form-control" name="rating" value="{{ rating }}" id="rating" placeholder="Rating" required>
			  </div>
			  <div class="text-center">
			  	<button type="submit" class="btn btn-primary text-center">Save</button>
		  	  </div>
			</form>

		</div>

	</div>

</body>

music/greedymusic/templates/greedymusic/genres.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>


	<div class="row">

		<div class="col-md-6 col-md-offset-3 text-center">

			

			<br/>

				{% if genre_list %}
					<div class="panel panel-success">
						  <div class="panel-heading">
						  	<a href="/greedymusic/genres">GENRES</a>
						  </div>
						  <!-- <div class="panel-body"> -->
						  	<table class="table table-striped">
						  		<tr>
						  		<td><b>ID</b></td>
						  		<td><b>Genre</b></td>
						  		<td><b>Options</b></td>
						  		</tr>

					{% for genre in genre_list %}

						
						  

							  	<tr>

							  		<td><a href="{% url 'greedymusic:detailGenre' genre.id %}">{{genre.id}}</a></td>


							  		<td>{{genre.genre_name}}</td>

							  		<td><a href="{% url 'greedymusic:editGenre' genre.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>

							  	</tr>

						  	
						

					{% endfor %}
						</table>
						  </div>
						<!-- </div> -->

				{% else %}

					<p>No genres available</p>

				{% endif %}
		</div>

	</div>

	<div class="row">

	<div class="col-md-4 col-md-offset-4 text-center">

		<button class="btn btn-success btn-md" onclick="window.location.href='/greedymusic/addGenre'">Add New Genre</button>

	</div>

</body>

music/greedymusic/templates/greedymusic/index.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>


	<div class="row">

		<div class="col-md-4 col-md-offset-4 text-center">

			<h4>What do you want to view?</h4>

			<br/>

			<div class="btn-group" role="group">
				<button class="btn btn-md btn-primary" onclick="window.location.href='tracks/1'">Tracks</button>
				<button class="btn btn-md btn-success" onclick="window.location.href='genres'">Genres</button>
			</div>

		</div>

	</div>

</body>

music/greedymusic/templates/greedymusic/search.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>


	<div class="row">

		<div class="col-md-4 col-md-offset-4 text-center">

			<div class="input-group">

				<div class="input-group-btn">

					<form method="POST" action="{% url 'greedymusic:search' %}">
						{% csrf_token %}

						<button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>

					

				</div>

				

					<input type="text" name="keyword" id="search" class="form-control" placeholder="Search">

				</form>

				<div class="input-group-btn">

					<button class="btn btn-default" type="button" onclick="document.getElementById('search').value='';"><span class="glyphicon glyphicon-remove-circle"></span></button>

				</div>

			</div>

		</div>

	</div>

	<div class="row">

		<div class="col-md-6 col-md-offset-3 text-center">

			

			<br/>

				{% if track_list %}
					<div class="panel panel-danger">
						  <div class="panel-heading">
						  	<a href="/greedymusic/tracks/1">TRACKS</a>
						  </div>
						  <!-- <div class="panel-body"> -->
						  	<table class="table table-striped">
						  		<tr>
						  		<td><b>ID</b></td>
						  		<td><b>Title</b></td>
						  		<td><b>Genre</b></td>
						  		<td><b>Rating</b></td>
						  		<td><b>Options</b></td>
						  		</tr>

					{% for track in track_list %}

						
						  

							  	<tr>

							  		<td><a href="{% url 'greedymusic:detailTrack' track.id %}">{{track.id}}</a></td>

							  		<td> {{track.title}}</td>


							  		<td>{{track.genre}}</td>
							  		<td>
							  		{% for i in track.rating %}
							  			<span class="glyphicon glyphicon-star" style="color:black"></span>
							  		{% endfor %}
							  		{% for i in track.remaining %}
							  			<span class="glyphicon glyphicon-star" style="color:#ddd"></span>
							  		{% endfor %}
							  		</td>
							  		<td><a href="{% url 'greedymusic:editTrack' track.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>

							  	</tr>

						  	
						

					{% endfor %}
						</table>
						  </div>
						<!-- </div> -->

				{% else %}

					<p>No tracks available</p>

				{% endif %}
		</div>

	</div>

	<div class="row">

	<div class="col-md-4 col-md-offset-4 text-center">

		<button class="btn btn-danger btn-md" onclick="window.location.href='/greedymusic/addTrack'">Add New Track</button>

	</div>

</body>

music/greedymusic/templates/greedymusic/track.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>


	<!-- <div class="row">

		<div class="col-md-4 col-md-offset-4 text-center">

			<div class="input-group">

				<div class="input-group-btn">

					<form method="POST" action="">

						<button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>

					</form>

				</div>

				<input type="text" id="search" class="form-control" placeholder="Search">

				<div class="input-group-btn">

					<button class="btn btn-default" type="button" onclick="document.getElementById('search').value='';"><span class="glyphicon glyphicon-remove-circle"></span></button>

				</div>

			</div>

		</div>

	</div> -->

	<div class="row">

		<div class="col-md-6 col-md-offset-3 text-center">
			<br/>

				{% if track %}
					<div class="panel panel-danger">
						  <div class="panel-heading">
						  	<a href="/greedymusic/tracks/1">TRACKS</a>
						  </div>
						  <!-- <div class="panel-body"> -->
						  	<table class="table table-striped">
						  		<tr>
						  		<td><b>ID</b></td>
						  		<td><b>Title</b></td>
						  		<td><b>Genre</b></td>
						  		<td><b>Rating</b></td>
						  		<td><b>Options</b></td>
						  		</tr>
							  	<tr>
							  		<td><a href="{% url 'greedymusic:detailTrack' track.id %}">{{track.id}}</a></td>

							  		<td> {{track.title}}</td>


							  		<td>{{track.genre}}</td>


							  		<td>{% for i in track.rating %}
							  			<span class="glyphicon glyphicon-star" style="color:black"></span>
							  		{% endfor %}
							  		{% for i in track.remaining %}
							  			<span class="glyphicon glyphicon-star" style="color:#ddd"></span>
							  		{% endfor %}</td>

							  		<td><a href="{% url 'greedymusic:editTrack' track.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>

							  	</tr>
						</table>
						  </div>
						<!-- </div> -->

				{% else %}

					<p>No tracks available</p>

				{% endif %}
		</div>

	</div>


</body>

music/greedymusic/templates/greedymusic/tracks.html
<!DOCTYPE html>
<html>

<head>
	
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'custom.css' %}" type="text/css">
</head>

<body>

	<nav class="navbar navbar-inverse" style="">
	  	<div class="container-fluid">
	    	<!-- <div class="navbar-header">
	      		<a class="navbar-brand" href="#">
	       			<h2>Greedymusic</h2>
	     		</a>
	   		</div> -->
	   		<div class="col-md-3 col-md-offset-5 text-center">
	   			<a class="navbar-brand title" href="/greedymusic">Greedymusic Webapp</a>
	   		</div>
	  	</div>
	</nav>


	<div class="row">

		<div class="col-md-4 col-md-offset-4 text-center">

			<div class="input-group">

				<div class="input-group-btn">

					<form method="POST" action="{% url 'greedymusic:search' %}">
						{% csrf_token %}

						<button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>

					

				</div>

				

					<input type="text" name="keyword" id="search" class="form-control" placeholder="Search">

				</form>

				<div class="input-group-btn">

					<button class="btn btn-default" type="button" onclick="document.getElementById('search').value='';"><span class="glyphicon glyphicon-remove-circle"></span></button>

				</div>

			</div>

		</div>

	</div>

	<div class="row">

		<div class="col-md-6 col-md-offset-3 text-center">

			

			<br/>

				{% if track_list %}
					<div class="panel panel-danger">
						  <div class="panel-heading">
						  	<a href="/greedymusic/tracks/1">TRACKS</a>
						  </div>
						  <!-- <div class="panel-body"> -->
						  	<table class="table table-striped">
						  		<tr>
						  		<td><b>ID</b></td>
						  		<td><b>Title</b></td>
						  		<td><b>Genre</b></td>
						  		<td><b>Rating</b></td>
						  		<td><b>Options</b></td>
						  		</tr>

					{% for track in track_list %}

						
						  

							  	<tr>

							  		<td><a href="{% url 'greedymusic:detailTrack' track.id %}">{{track.id}}</a></td>

							  		<td> {{track.title}}</td>


							  		<td>{{track.genre}}</td>


							  		<td>{% for i in track.rating %}
							  			<span class="glyphicon glyphicon-star" style="color:black"></span>
							  		{% endfor %}
							  		{% for i in track.remaining %}
							  			<span class="glyphicon glyphicon-star" style="color:#ddd"></span>
							  		{% endfor %}</td>

							  		<td><a href="{% url 'greedymusic:editTrack' track.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>

							  	</tr>

						  	
						

					{% endfor %}
						</table>
						  </div>
						<!-- </div> -->
						<nav>
						  <ul class="pagination">
					{% for i in pages %}
						
						    
						    <li><a href="/greedymusic/tracks/{{i}}">Page {{i}}</a></li>
						    
						    
						  

					{%endfor%}
					</ul>
						</nav>
				{% else %}

					<p>No tracks available</p>

				{% endif %}
		</div>

	</div>

	<div class="row">

	<div class="col-md-4 col-md-offset-4 text-center">

		<button class="btn btn-danger btn-md" onclick="window.location.href='/greedymusic/addTrack'">Add New Track</button>

	</div>

</body>